// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfysjxptsktpwhrkrrmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmeXNqeHB0c2t0cHdocmtycm1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MzQyNTcsImV4cCI6MjA2NjQxMDI1N30.8Oxa44vZphzWF6eqW7I9gc2HtzNfw_YCGdznA-ef-ks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);